[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "mediascan"
version = "1.2.1"
requires-python = ">=3.11"
authors = [{ name = "moongas.org", email = "moongas.org@gmail.com" }]
maintainers = [{ name = "moongas.org", email = "moongas.org@gmail.com" }]
description = "A Python project for working with moongas mediascan database and metadata files."
readme = "README.md"
license = { file = "LICENSE.txt" }
keywords = [
  "moongas", 
  "mediascan", 
  "music",
  "metadata",
  "database",
  "python",
  "audio",
  "media",
  "tagging",
  "file management",
  "file organization"
]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  'Intended Audience :: End Users/Desktop',
  'Intended Audience :: Education',
  'Intended Audience :: Science/Research',
  'Topic :: Utilities',
  'License :: OSI Approved :: GNU Lesser General Public License v3 (LGPLv3)',
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: 3 :: Only",
]

dependencies = [
  "dataclass-wizard[yaml]>=0.39.1",
  "pandas>=2.2.3 ; python_version < '3.11'",
  "pandas>=3.0.5 ; python_version >= '3.11'",
  "pyaml>=26.7.0",
  "sqlalchemy>=2.0.52",
]

[project.optional-dependencies]
dev = [
  "ruff>=0.1.0",
  "pytest>=9.1.1",
]

[project.urls]
"Homepage" = "https://github.com/moongas-org/moongas-mediascan-python"
Documentation = "https://github.com/moongas-org/moongas-mediascan-python"
Repository = "https://github.com/moongas-org/moongas-mediascan-python.git"
"Bug Tracker" = "https://github.com/moongas-org/moongas-mediascan-python/issues"
Changelog = "https://github.com/moongas-org/moongas-mediascan-python/blob/master/CHANGELOG.md"

[tool.setuptools.package-data]
mediascan = ['py.typed']

[tool.setuptools.packages.find]
where = ["src"]
include = ["mediascan*"]

[tool.pytest.ini_options]
pythonpath = [
  "."
]
testpaths = [
  "tests"
]
norecursedirs = [
  ".env*",
  ".venv*",
  ".git",
  ".tox",
  "build",
  "dist",
  "env*",
  "venv*",
  "docs",
  "__pycache__",
  "out"
]
addopts = [
  "--ignore=.git",
  "--ignore=.tox",
  "--ignore=build",
  "--ignore=dist",
  "--ignore=__pycache__",
  "--ignore=out"
]

[tool.ruff]
# Set the maximum line length to match your GitHub Actions setup
line-length = 127

[tool.ruff.lint]
# Enable Flake8 syntax/error equivalents (E9, F63, F7, F82)
# "E" and "F" enable pycodestyle errors and Pyflakes
select = ["E9", "F63", "F7", "F82"]

# Enable McCabe complexity checking (equivalent to flake8 --max-complexity=10)
[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.mypy]
mypy_path = "typings"

[[tool.mypy.overrides]]
module = "*.pyi"
ignore_errors = true
